/**
 * Workflow Types — Shared type definitions for structured, reusable workflows.
 *
 * A WorkflowDefinition is generated by parsing a recording manifest via Claude,
 * then executed by the workflow executor feeding it as structured context to the agent loop.
 */

export interface WorkflowDefinition {
  id: string;                              // generated UUID
  name: string;                            // human-readable name from narration/description
  description: string;                     // what this workflow does
  createdFrom: string;                     // sessionId of the source recording
  createdAt: string;                       // ISO timestamp
  applications: ApplicationMapping[];      // apps used and their control layers
  variables: WorkflowVariable[];           // data that changes per execution
  steps: WorkflowStep[];                   // the ordered steps
  loops?: LoopDefinition;                  // if the workflow repeats over a set of items
  rules?: BusinessRule[];                  // decision points and business logic
}

export interface ApplicationMapping {
  name: string;          // "Microsoft Excel", "Google Chrome", "TimeTracker"
  type: 'desktop' | 'browser' | 'system';
  preferredLayer: 'skill' | 'shell' | 'cdp' | 'accessibility' | 'vision';
  url?: string;          // for web apps
}

export interface WorkflowVariable {
  name: string;          // e.g. "employeeName", "billingAddress"
  description: string;   // what this variable represents
  source: string;        // where it comes from: "Excel cell A{{row}}", "CRM field", "user input"
  type: 'string' | 'number' | 'date' | 'boolean';
}

export interface WorkflowStep {
  id: number;
  description: string;           // human-readable: "Read employee name from Excel"
  application: string;           // which app this step uses
  layer: 'skill' | 'shell' | 'cdp' | 'accessibility' | 'vision';
  action: string;                // the action type: "navigate", "read_field", "enter_field", "click_button", "open_app", etc.
  params: Record<string, unknown>; // action-specific parameters (with {{variable}} placeholders)
  output?: string;               // variable name to store the result in
  verification?: string;         // how to verify this step succeeded
  fallbackLayer?: string;        // fallback if preferred layer fails
}

export interface LoopDefinition {
  over: string;          // what we're iterating: "employees", "invoices", "customers"
  source: string;        // where the list comes from: "Excel rows A2:A50"
  variable: string;      // loop variable name: "currentEmployee"
  stepsInLoop: number[]; // which step IDs are inside the loop
}

export interface BusinessRule {
  condition: string;     // "hours > 40", "amount > previousAmount * 1.5"
  action: string;        // "apply overtime rate", "flag for review"
  source: string;        // where this rule was identified: "narration at 00:32"
}
