/**
 * Generate Config — Creates src/build-config.ts with baked-in values before tsc runs.
 *
 * Usage:
 *   WFA_BRIDGE_URL=wss://... WFA_ANTHROPIC_KEY=sk-ant-... npx tsx scripts/generate-config.ts
 *
 * This replaces a shell script to avoid quoting/injection issues (P1 fix).
 * JSON.stringify handles all special characters safely.
 */

import * as fs from 'fs';
import * as path from 'path';

const config = {
  BRIDGE_URL: process.env.WFA_BRIDGE_URL ?? 'ws://localhost:8765',
  ANTHROPIC_KEY: process.env.WFA_ANTHROPIC_KEY ?? '',
};

const output = [
  '// AUTO-GENERATED by scripts/generate-config.ts -- do not edit',
  '// WARNING: This key is embedded in the build artifact. Do not use production keys.',
  ...Object.entries(config).map(
    ([key, value]) => `export const ${key} = ${JSON.stringify(value)} as const;`
  ),
  '',
].join('\n');

const outputPath = path.join(__dirname, '../src/build-config.ts');
fs.writeFileSync(outputPath, output, 'utf-8');

const maskedKey = config.ANTHROPIC_KEY
  ? `${config.ANTHROPIC_KEY.slice(0, 10)}...${config.ANTHROPIC_KEY.slice(-4)}`
  : '(empty)';
console.log(`Generated src/build-config.ts (bridge: ${config.BRIDGE_URL}, key: ${maskedKey})`);
