/**
 * Generate Config — Creates src/build-config.ts with baked-in values before tsc runs.
 *
 * Usage:
 *   WFA_BRIDGE_URL=wss://... WFA_ANTHROPIC_KEY=sk-ant-... npx tsx scripts/generate-config.ts
 *
 * This replaces a shell script to avoid quoting/injection issues (P1 fix).
 * JSON.stringify handles all special characters safely.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';

// Load .env from project root (one level up from local-agent/).
// When run via `npx tsx`, __dirname may be `.`, so use process.cwd() as a fallback.
const scriptDir = path.resolve(__dirname);
const localAgentDir = scriptDir.endsWith('/scripts') ? path.join(scriptDir, '..') : process.cwd();
const envPath = path.join(localAgentDir, '../.env');
// Use override: true so .env values take precedence over shell environment
// (e.g. a stale ANTHROPIC_API_KEY in the shell won't shadow the .env value)
dotenv.config({ path: envPath, override: true });

const config = {
  BRIDGE_URL: process.env.WFA_BRIDGE_URL ?? 'wss://wfa-bridge.fly.dev',
  ANTHROPIC_KEY: process.env.WFA_ANTHROPIC_KEY ?? process.env.ANTHROPIC_API_KEY ?? '',
};

const output = [
  '// AUTO-GENERATED by scripts/generate-config.ts -- do not edit',
  '// WARNING: This key is embedded in the build artifact. Do not use production keys.',
  ...Object.entries(config).map(
    ([key, value]) => `export const ${key} = ${JSON.stringify(value)} as const;`
  ),
  '',
].join('\n');

const outputPath = path.join(__dirname, '../src/build-config.ts');
fs.writeFileSync(outputPath, output, 'utf-8');

const maskedKey = config.ANTHROPIC_KEY
  ? `${config.ANTHROPIC_KEY.slice(0, 10)}...${config.ANTHROPIC_KEY.slice(-4)}`
  : '(empty)';
console.log(`Generated src/build-config.ts (bridge: ${config.BRIDGE_URL}, key: ${maskedKey})`);
