// AUTO-GENERATED by scripts/generate-config.ts -- do not edit
// WARNING: This key is embedded in the build artifact. Do not use production keys.
// Default dev config — overwritten by `npm run generate-config` for distribution builds.
export const BRIDGE_URL = 'ws://localhost:8765' as const;
export const ANTHROPIC_KEY = '' as const;
