// AUTO-GENERATED by scripts/generate-config.ts -- do not edit
// WARNING: This key is embedded in the build artifact. Do not use production keys.
export const BRIDGE_URL = "wss://wfa-bridge.fly.dev" as const;
export const ANTHROPIC_KEY = "" as const;
